name: Testing

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.66.0
          cache: false
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run test-all
